version: '3.8'
services:
  api:
    build:
      context: ./Api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
    environment:
      - NODE_ENV=development

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
    environment:
      - NODE_ENV=development
